"""Shared dataclasses and data structures used across quant modules."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any


@dataclass(slots=True)
class MarketBar:
	"""Represents a single OHLCV bar for a trading symbol."""

	symbol: str
	timestamp: datetime
	open: float
	high: float
	low: float
	close: float
	volume: float


@dataclass(slots=True)
class IndicatorSnapshot:
	"""Collection of indicator values calculated for a symbol at a point in time."""

	symbol: str
	timestamp: datetime
	values: dict[str, Any] = field(default_factory=dict)
	metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class TradeSignal:
	"""Decision produced by an Agent for a particular symbol."""

	symbol: str
	side: str  # BUY, SELL, or HOLD
	quantity: float
	confidence: float
	metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class AccountSnapshot:
	"""Snapshot of account balances and positions."""

	cash: float
	positions: dict[str, float] = field(default_factory=dict)
	timestamp: datetime = field(default_factory=datetime.utcnow)


@dataclass(slots=True)
class PromptPayload:
	"""Prompt and supplemental metadata passed to an Agent."""

	content: str
	metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class AgentResponse:
	"""Response returned by an Agent prior to signal validation."""

	raw_text: str
	signals: list[TradeSignal] = field(default_factory=list)
	latency_ms: int | None = None
	metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class BacktestReport:
	"""Aggregate metrics generated by the backtest engine."""

	started_at: datetime
	ended_at: datetime
	metrics: dict[str, float] = field(default_factory=dict)
	artifacts: dict[str, Any] = field(default_factory=dict)
